/**
  * This file was auto-generated by .swagger-ts/gen-request.mjs.
  * Do not make direct changes to the file.
  * Please change src/services/api/swagger-api.ts, then regenerate it.
  */

import { fetcher } from '@/services/instance/swagger-api-request-instance'

export const uploadFile = fetcher.path('/pet/{petId}/uploadImage').method('post').create()

export const updatePet = fetcher.path('/pet').method('put').create()

export const addPet = fetcher.path('/pet').method('post').create()

export const findPetsByStatus = fetcher.path('/pet/findByStatus').method('get').create()

export const findPetsByTags = fetcher.path('/pet/findByTags').method('get').create()

export const getPetById = fetcher.path('/pet/{petId}').method('get').create()

export const updatePetWithForm = fetcher.path('/pet/{petId}').method('post').create()

export const deletePet = fetcher.path('/pet/{petId}').method('delete').create()

export const placeOrder = fetcher.path('/store/order').method('post').create()

export const getOrderById = fetcher.path('/store/order/{orderId}').method('get').create()

export const deleteOrder = fetcher.path('/store/order/{orderId}').method('delete').create()

export const getInventory = fetcher.path('/store/inventory').method('get').create()

export const createUsersWithArrayInput = fetcher.path('/user/createWithArray').method('post').create()

export const createUsersWithListInput = fetcher.path('/user/createWithList').method('post').create()

export const getUserByName = fetcher.path('/user/{username}').method('get').create()

export const updateUser = fetcher.path('/user/{username}').method('put').create()

export const deleteUser = fetcher.path('/user/{username}').method('delete').create()

export const loginUser = fetcher.path('/user/login').method('get').create()

export const logoutUser = fetcher.path('/user/logout').method('get').create()

export const createUser = fetcher.path('/user').method('post').create()
