/**
  * This file was auto-generated by .swagger-ts/gen-request.mjs.
  * Do not make direct changes to the file.
  * Please change src/services/api/custom-api.ts, then re-generate it.
  */

import type { FetchArgType, FetchErrorType, FetchReturnType } from 'openapi-typescript-fetch'

export {}

declare global {
  /* updatePetCustom */
  type updatePetCustomArg = FetchArgType<typeof updatePetCustom>
  type updatePetCustomRet = FetchReturnType<typeof updatePetCustom>
  type updatePetCustomErr = FetchErrorType<typeof updatePetCustom>
  /* addPetCustom */
  type addPetCustomArg = FetchArgType<typeof addPetCustom>
  type addPetCustomRet = FetchReturnType<typeof addPetCustom>
  type addPetCustomErr = FetchErrorType<typeof addPetCustom>
  /* findPetsByStatusCustom */
  type findPetsByStatusCustomArg = FetchArgType<typeof findPetsByStatusCustom>
  type findPetsByStatusCustomRet = FetchReturnType<typeof findPetsByStatusCustom>
  type findPetsByStatusCustomErr = FetchErrorType<typeof findPetsByStatusCustom>
}