/**
  * This file was auto-generated by .swagger-ts/gen-request.mjs.
  * Do not make direct changes to the file.
  * Please change src/services/api/swagger-api.ts, then re-generate it.
  */

import type { FetchArgType, FetchErrorType, FetchReturnType } from 'openapi-typescript-fetch'

export {}

declare global {
  /* uploadFile */
  type uploadFileArg = FetchArgType<typeof uploadFile>
  type uploadFileRet = FetchReturnType<typeof uploadFile>
  type uploadFileErr = FetchErrorType<typeof uploadFile>
  /* updatePet */
  type updatePetArg = FetchArgType<typeof updatePet>
  type updatePetRet = FetchReturnType<typeof updatePet>
  type updatePetErr = FetchErrorType<typeof updatePet>
  /* addPet */
  type addPetArg = FetchArgType<typeof addPet>
  type addPetRet = FetchReturnType<typeof addPet>
  type addPetErr = FetchErrorType<typeof addPet>
  /* findPetsByStatus */
  type findPetsByStatusArg = FetchArgType<typeof findPetsByStatus>
  type findPetsByStatusRet = FetchReturnType<typeof findPetsByStatus>
  type findPetsByStatusErr = FetchErrorType<typeof findPetsByStatus>
  /* findPetsByTags */
  type findPetsByTagsArg = FetchArgType<typeof findPetsByTags>
  type findPetsByTagsRet = FetchReturnType<typeof findPetsByTags>
  type findPetsByTagsErr = FetchErrorType<typeof findPetsByTags>
  /* getPetById */
  type getPetByIdArg = FetchArgType<typeof getPetById>
  type getPetByIdRet = FetchReturnType<typeof getPetById>
  type getPetByIdErr = FetchErrorType<typeof getPetById>
  /* updatePetWithForm */
  type updatePetWithFormArg = FetchArgType<typeof updatePetWithForm>
  type updatePetWithFormRet = FetchReturnType<typeof updatePetWithForm>
  type updatePetWithFormErr = FetchErrorType<typeof updatePetWithForm>
  /* deletePet */
  type deletePetArg = FetchArgType<typeof deletePet>
  type deletePetRet = FetchReturnType<typeof deletePet>
  type deletePetErr = FetchErrorType<typeof deletePet>
  /* placeOrder */
  type placeOrderArg = FetchArgType<typeof placeOrder>
  type placeOrderRet = FetchReturnType<typeof placeOrder>
  type placeOrderErr = FetchErrorType<typeof placeOrder>
  /* getOrderById */
  type getOrderByIdArg = FetchArgType<typeof getOrderById>
  type getOrderByIdRet = FetchReturnType<typeof getOrderById>
  type getOrderByIdErr = FetchErrorType<typeof getOrderById>
  /* deleteOrder */
  type deleteOrderArg = FetchArgType<typeof deleteOrder>
  type deleteOrderRet = FetchReturnType<typeof deleteOrder>
  type deleteOrderErr = FetchErrorType<typeof deleteOrder>
  /* getInventory */
  type getInventoryArg = FetchArgType<typeof getInventory>
  type getInventoryRet = FetchReturnType<typeof getInventory>
  type getInventoryErr = FetchErrorType<typeof getInventory>
  /* createUsersWithArrayInput */
  type createUsersWithArrayInputArg = FetchArgType<typeof createUsersWithArrayInput>
  type createUsersWithArrayInputRet = FetchReturnType<typeof createUsersWithArrayInput>
  type createUsersWithArrayInputErr = FetchErrorType<typeof createUsersWithArrayInput>
  /* createUsersWithListInput */
  type createUsersWithListInputArg = FetchArgType<typeof createUsersWithListInput>
  type createUsersWithListInputRet = FetchReturnType<typeof createUsersWithListInput>
  type createUsersWithListInputErr = FetchErrorType<typeof createUsersWithListInput>
  /* getUserByName */
  type getUserByNameArg = FetchArgType<typeof getUserByName>
  type getUserByNameRet = FetchReturnType<typeof getUserByName>
  type getUserByNameErr = FetchErrorType<typeof getUserByName>
  /* updateUser */
  type updateUserArg = FetchArgType<typeof updateUser>
  type updateUserRet = FetchReturnType<typeof updateUser>
  type updateUserErr = FetchErrorType<typeof updateUser>
  /* deleteUser */
  type deleteUserArg = FetchArgType<typeof deleteUser>
  type deleteUserRet = FetchReturnType<typeof deleteUser>
  type deleteUserErr = FetchErrorType<typeof deleteUser>
  /* loginUser */
  type loginUserArg = FetchArgType<typeof loginUser>
  type loginUserRet = FetchReturnType<typeof loginUser>
  type loginUserErr = FetchErrorType<typeof loginUser>
  /* logoutUser */
  type logoutUserArg = FetchArgType<typeof logoutUser>
  type logoutUserRet = FetchReturnType<typeof logoutUser>
  type logoutUserErr = FetchErrorType<typeof logoutUser>
  /* createUser */
  type createUserArg = FetchArgType<typeof createUser>
  type createUserRet = FetchReturnType<typeof createUser>
  type createUserErr = FetchErrorType<typeof createUser>
}